### ISSUE TITLE
an error occurred during export

### ISSUE THREAD

**Issue by fjremnav** [sithu31296/semantic-segmentation#13]
When I run "python tools/export.py --cfg configs/custom.yaml", I got the following error:

Traceback (most recent call last):
  File "tools/export.py", line 66, in <module>
    main(cfg)
  File "tools/export.py", line 43, in main
    model = eval(cfg['MODEL']['NAME'])(cfg['MODEL']['BACKBONE'], len(eval(cfg['DATASET']['NAME']).PALETTE))
  File "<string>", line 1, in <module>
NameError: name 'cityscapes' is not defined

Any idea how to fix it?

Thanks,

**Comment by sithu31296** [comment]
Fixed the issue in https://github.com/sithu31296/semantic-segmentation/commit/cf2805dda1ac4b8af04c161d6959e6d1f4e3fe1b
