### ISSUE TITLE
backbone of ddrnet_23_city.pth

### ISSUE THREAD

**Issue by fjremnav** [sithu31296/semantic-segmentation#14]
I am able to convert ddrnet_23slim_city.pth to onnx model using backbone DDRNet-23slim
However, I got a lot of mismatch when converting ddrnet_23_city.pth to onnx model using backbone DDRNet-23 or DDRNet
What backbone name should I use in the config.yaml?
Thanks,

**Comment by bbbts** [comment]
> DDRNet-23 is not supported anymore. So, your error is fine. I forgot to update the weights.

please let me know from where I can find the backbone weights. Thnakss!
