### ISSUE TITLE
colab result not good

### ISSUE THREAD

**Issue by ccl-private** [sithu31296/semantic-segmentation#16]
![image](https://user-images.githubusercontent.com/36214675/140001847-dfb297eb-32c1-499c-af14-f75d3c7d782a.png)

**Comment by sithu31296** [comment]
Please uncomment the following lines in the pretrained weights downloading part.
`import gdown`

`gdown.download(url, output, quiet=False)`

**Comment by ccl-private** [comment]
thank you~
![image](https://user-images.githubusercontent.com/36214675/140003978-ce00a9cb-d7f5-4b25-8978-9ff4e576ca3b.png)
it works.
