### ISSUE TITLE
No test.py?

### ISSUE THREAD

**Issue by Xuefei98** [sithu31296/semantic-segmentation#17]
I was about to testing the pretrained model on the dataset that I am planning on using but didn't see a test..py available

**Comment by sithu31296** [comment]
You can use tools/infer.py

**Comment by Xuefei98** [comment]
My bad! Sorry i thought the name would be test.py. Thanks! But another problem I have is when I run the infer.py with configuration file ade20k.yml and test mode segformer.b3.ade.pth. It returns size mismatch error. But segformer.b3.ade.pth is the default model that the file has.

**Comment by Xuefei98** [comment]
size mismatch for decode_head.linear_pred.weight: copying a param with shape torch.Size([150, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([150, 256, 1, 1]).

**Comment by Xuefei98** [comment]
SOLUTION: VARIANT need to be changed too.
