### ISSUE TITLE
Pretrained model on Lapa

### ISSUE THREAD

**Issue by gitlabspy** [sithu31296/semantic-segmentation#18]
Thanks for your wonderful work! I wonder if there is any pretrained bisenetv2 (or other models) on dataset lapa you can share with us?

**Comment by sithu31296** [comment]
Sadly, I don't have any models trained on lapa dataset.

**Comment by gitlabspy** [comment]
Thanks for replying. May I ask if you have models trained on any face parsing dataset that can share with us?

**Comment by sithu31296** [comment]
I don't have any other models except the ones in [MODELS](https://github.com/sithu31296/semantic-segmentation/blob/main/docs/MODELS.md#face-parsing). These models are trained on HELEN dataset but please keep in mind that I only tested the performance of the models on face parsing datasets. If you have great machine and more tuning, you can get better results.
