### ISSUE TITLE
Get wrong result when I rerun demo

### ISSUE THREAD

**Issue by kiashann** [sithu31296/semantic-segmentation#19]
Hi, I ran notebook for segmentation. but I got very bad result.
Could you please tell me why it was happened. The link of[ notebook](https://colab.research.google.com/drive/1hgEn_qnydTQqJijSzJ6IqrVOpeX6pEc7?usp=sharing).

@sithu31296

**Comment by sithu31296** [comment]
Hello, thanks for reporting this. This is an issue related with gdown. Already fixed in [latest commit](https://github.com/sithu31296/semantic-segmentation/commit/958ed542aa68003eb0a2b0799cf5cecfe6c7587c).
