### ISSUE TITLE
ModuleNotFoundError: No module named 'semseg'

### ISSUE THREAD

**Issue by Shawn207** [sithu31296/semantic-segmentation#25]
Hi there,
When I tried to run infer.py, I got the following error:
`(sotas) xzhan2@cerlab27:~/semantic-segmentation$ python tools/infer.py --cfg configs/custom.yaml
Traceback (most recent call last):
  File "tools/infer.py", line 12, in <module>
    from semseg.models import *
ModuleNotFoundError: No module named 'semseg'`
I also tried to append the path to /semseg into sys.path, but it did not solve the problem. 
Could you please give a bit suggestions?
Thanks

**Comment by sithu31296** [comment]
You have to clone the repo and install with `pip install -e .`

**Comment by Shawn207** [comment]
Thanks!

sithu3 ***@***.***>于2022年4月18日 周一11:12写道：
