### ISSUE TITLE
Some updates on arxiv papers that have been accepted to conferences/journals

### ISSUE THREAD

**Issue by dahyun-kang** [sithu31296/semantic-segmentation#27]
Hello,

Thank you for making this great repo publicly available. This helps me a lot!
Here are some up-to-date conference venues of arxiv paper info in README.md.
Please have a look and consider updating README.md.

SegFormer: Neurips 2021
PVTv2: CVMJ 2022 (PVT: ICCV 2021)
ResT: Neurips 2021
Poolformer: CVPR 2022
ConvNeXt: CVPR 2022

Have a great day! :smiley: 

Dahyun.

**Comment by sithu31296** [comment]
Hi, Thanks for the correction. I will update it.
