### ISSUE TITLE
Double Checking implementation detail in SegFormerHead

### ISSUE THREAD

**Issue by RahulSinghalChicago** [sithu31296/semantic-segmentation#29]
The paper on [SegFormer](https://arxiv.org/pdf/2105.15203.pdf) suggests an All MLP decoder.

![Screen Shot 2022-04-23 at 3 03 57 AM](https://user-images.githubusercontent.com/3970349/164886085-eeb06539-1205-429a-ab4a-481eb1fe83b8.png)

The SegformerHead.py shows the use of a Conv2D for the final layer.

![Screen Shot 2022-04-23 at 3 06 18 AM](https://user-images.githubusercontent.com/3970349/164886111-b6e48426-bf45-4820-aa1a-0414e1b92f70.png)

Can you help me understand if this is a deviation from the paper or mentioned in a followup paper somewhere?  I apologize in advance if there is an obvious answer.

**Comment by sithu31296** [comment]
1x1 conv is basically the same as linear operation. In segmentation, 1x1 conv is usually used as the last layer. You can also check the [official segformer implementation](https://github.com/NVlabs/SegFormer/blob/master/mmseg/models/decode_heads/segformer_head.py#L62).

**Comment by RahulSinghalChicago** [comment]
Thank you!
