### ISSUE TITLE
ImageDraw.textbbox Attribute error in Visualize.py function "draw_text" when calling infer.py

### ISSUE THREAD

**Issue by mhmd-mst** [sithu31296/semantic-segmentation#33]
I am running infer.py and I get this error, any idea why?
Traceback (most recent call last):
  File "tools/infer.py", line 100, in <module>
    segmap,oversegmap,image = semseg.predict(str(test_file), cfg['TEST']['OVERLAY'])
  File "tools/infer.py", line 73, in predict
    seg_map,over_seg_map,image = self.postprocess(torch.tensor(image1), seg_map, overlay)
  File "tools/infer.py", line 60, in postprocess
    image = draw_text(seg_image, seg_map, self.labels)
  File "/content/trial/semseg/utils/visualize.py", line 28, in draw_text
    bbox = draw.textbbox(center, cls, font=fonts)
AttributeError: 'ImageDraw' object has no attribute 'textbbox'

**Comment by sithu31296** [comment]
what is your pillow version? Mine is 9.0.0. If lower than that, please try to upgrade.

**Comment by mhmd-mst** [comment]
yeah it was version problem, Thank a lot for you help!!
