### ISSUE TITLE
Where do I get mit_b3.pth file? 

### ISSUE THREAD

**Issue by hatsumikana** [sithu31296/semantic-segmentation#35]
Hello! Thank you very much for the nice git repo! May I know where I can find the backbone model's weight file if I am using SegFormer MiT-B3? Thank you once again :)

**Comment by hatsumikana** [comment]
And what is the difference between the backbone weights and pretrained weights?

**Comment by BooHwang** [comment]
> Hello! Thank you very much for the nice git repo! May I know where I can find the backbone model's weight file if I am using SegFormer MiT-B3? Thank you once again :)

https://drive.google.com/file/d/1-OmW3xRD3WAbJTzktPC-VMOF5WMsN8XT/view?usp=sharing
