### ISSUE TITLE
How to use PSA

### ISSUE THREAD

**Issue by zzc-ai** [sithu31296/semantic-segmentation#5]

**Comment by sithu31296** [comment]
Hello,
Check the following file https://github.com/sithu31296/semantic-segmentation/blob/main/models/modules/psa.py and usage is in the comments. As said in the paper, PSA module can be added after first 3x3 conv layer in the ResNet block.

**Comment by zzc-ai** [comment]
thanks,but its on the resnet model,how it can be worked on mobilenetv2?

**Comment by sithu31296** [comment]
I haven't check with mobilenet yet. But I think PSA can be added after depth-wise conv layer in InvertedResidual block. You can try to experiment it yourself.

**Comment by sithu31296** [comment]
I'm closing this issue, since I've already answered your question.

**Comment by zzc-ai** [comment]
thanks,your idea very helpful ,you are the kind person who fasetest reply my issue .
