### ISSUE TITLE
loss is nan

### ISSUE THREAD

**Issue by zhgyu** [sithu31296/semantic-segmentation#6]
Hello, I use the cityscapes.yaml file. After more than 200 epochs, the loss is infinite. Do you have any good solutions?

![image](https://user-images.githubusercontent.com/49664151/132933898-31aaf3a4-e378-4847-b6ee-edbb90a70a71.png)

**Comment by zhgyu** [comment]
![image](https://user-images.githubusercontent.com/49664151/132933888-4b2adb18-44ce-4b66-b025-e1f38538c577.png)

**Comment by StuLiu** [comment]
Hi! Could you please show me how do you solve this problem?
My solusion:
![image](https://user-images.githubusercontent.com/19245323/165671494-72d6c6cc-f097-477b-bb88-f3f4171768e7.png)
