### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (18) at non-singleton dimension 1

### ISSUE THREAD

**Issue by fajilatun** [sithu31296/semantic-segmentation#9]
I have 18 classes using the cityscapes dataset, and I used to train my own images but I get this error from the Dice loss function at this point:
 tp = torch.sum(targets*preds, dim=(2, 3))
RuntimeError: The size of tensor a (4) must match the size of tensor b (18) at non-singleton dimension 1

**Comment by sithu31296** [comment]
To use the dice loss, your label shape should be in shape [B, C, H, W].
check here https://github.com/sithu31296/semantic-segmentation/blob/main/utils/losses.py#L62.

So, you have to prepare the label image in a color coded channel instead of the individual pixel being a class number.

**Comment by fajilatun** [comment]
My label shape is in [B,C,H,W]. However, my label shape is [B,4,H,W] and the prediction gives [B,18,H,W]. How do I approach this?

**Comment by sithu31296** [comment]
You need to convert the label image to one-hot channel [B, num_classes, H, W] to get the same shape as in model prediction.
See the code below:

label = torch.randint(0, 255, (224, 224, 3))
out = torch.zeros(19, 224, 224)
colors = torch.tensor([[random.randint(0, 255) for _ in range(3)] for _ in range(19)])

for i, color in enumerate(colors):
  mask = torch.eq(label, color)
  cls_map = torch.all(mask, dim=-1)
  out[i] = cls_map
